### ISSUE TITLE
Cannot run Fire.app on Windows

### ISSUE THREAD

**Issue by ajwl** [KKBOX/FireApp#305]
I'm trying to run Fire.app for the first time on Windows 7. But it's failing and I'm getting the following error message. Any idea what I can do to run Fire.app?

> setting default path failed: problem creating X509 Aux certificate: java.io.IOException: corrupted stream - out of bounds length found
org/jruby/ext/openssl/X509Store.java:165:in `set_default_paths'
/C:/Users/anna.leach/fire.app/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:31:in `SSLContext'
/C:/Users/anna.leach/fire.app/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:22:in `SSL'
/C:/Users/anna.leach/fire.app/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:21:in `OpenSSL'
/C:/Users/anna.leach/fire.app/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:20:in `(root)'
org/jruby/RubyKernel.java:1087:in `load'
/C:/Users/anna.leach/fire.app/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/openssl/ssl-internal.rb:1:in `(root)'
org/jruby/RubyKernel.java:1071:in `require'
/C:/Users/anna.leach/fire.app/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54:in `require'
file:/C:/Users/anna.leach/fire.app/fire-app.jar!/require_patch.rb:6:in `require'
/C:/Users/anna.leach/fire.app/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/openssl/ssl-internal.rb:4:in `(root)'
org/jruby/RubyKernel.java:1087:in `load'
/C:/Users/anna.leach/fire.app/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl.rb:1:in `(root)'
org/jruby/RubyKernel.java:1071:in `require'
/C:/Users/anna.leach/fire.app/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54:in `require'
file:/C:/Users/anna.leach/fire.app/fire-app.jar!/require_patch.rb:6:in `require'
/C:/Users/anna.leach/fire.app/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl.rb:21:in `(root)'
org/jruby/RubyKernel.java:1071:in `require'
/C:/Users/anna.leach/fire.app/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54:in `require'
file:/C:/Users/anna.leach/fire.app/fire-app.jar!/require_patch.rb:6:in `require'
/C:/Users/anna.leach/fire.app/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/jopenssl/load.rb:1:in `(root)'
org/jruby/RubyKernel.java:1071:in `require'
/C:/Users/anna.leach/fire.app/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54:in `require'
file:/C:/Users/anna.leach/fire.app/fire-app.jar!/require_patch.rb:6:in `require'
/C:/Users/anna.leach/fire.app/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/jopenssl/load.rb:24:in `(root)'
org/jruby/RubyKernel.java:1071:in `require'
/C:/Users/anna.leach/fire.app/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54:in `require'
file:/C:/Users/anna.leach/fire.app/fire-app.jar!/require_patch.rb:6:in `require'
/C:/Users/anna.leach/fire.app/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/openssl.rb:1:in `(root)'
org/jruby/RubyKernel.java:1071:in `require'
/C:/Users/anna.leach/fire.app/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54:in `require'
file:/C:/Users/anna.leach/fire.app/fire-app.jar!/require_patch.rb:6:in `require'
/C:/Users/anna.leach/fire.app/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/openssl.rb:1:in `(root)'
org/jruby/RubyKernel.java:1071:in `require'
C:/Users/anna.leach/fire.app/lib/ruby/common/rest-client-1.7.2/lib/restclient.rb:1:in `(root)'
C:/Users/anna.leach/fire.app/lib/ruby/common/rest-client-1.7.2/lib/restclient.rb:2:in `(root)'

**Comment by hlb** [comment]
@ajwl hello, when does it happen? where is your project folder?

**Comment by ajwl** [comment]
It happens just after I downloaded fire app, extracted it and tried to run it for the first time. The project folder was saved on my user profile: C:/Users/anna.leach/fire.app

**Comment by hlb** [comment]
@ajwl can you try to move to C:\ and try again?

**Comment by ajwl** [comment]
Doesn't run from the C:/ either. :(  Same error... 
![fireproblem](https://cloud.githubusercontent.com/assets/10324129/9360151/8ac2f738-468c-11e5-970b-f29f33967ab0.jpg)

**Comment by hlb** [comment]
@ajwl it happens when you run Fire.app at the beginning? I wonder if your Fire.app binary is broken. Can you re-download it and try again?
