### ISSUE TITLE
windows板fireapp問題，選擇監看資料夾後，出現的錯誤。

### ISSUE THREAD

**Issue by doublinlin** [KKBOX/FireApp#314]
如下圖，我選擇監看這個資料夾後，馬上出現的訊息。
然後我再貼一次文字。
(https://user-images.githubusercontent.com/31687957/56015242-f01db880-5d2a-11e9-9306-2ab3017f11fa.png)
------------------------------------------------------------------------------------------------
Unknown error - Unknown Error (123) - C:\Users\Bigdata-A\Documents\pin\軟體\網頁撰寫\fire.app.windows.1.14\fire.app\lib\ruby\compass_extensions\bootstrap-sass-3.2.0.1\assets\stylesheets\bootstrap.scss
org/jruby/RubyFile.java:941:in `mtime'
C:/Users/Bigdata-A/Documents/pin/軟體/網頁撰寫/fire.app.windows.1.14/fire.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/importers/filesystem.rb:33:in `mtime'
C:/Users/Bigdata-A/Documents/pin/軟體/網頁撰寫/fire.app.windows.1.14/fire.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/staleness_checker.rb:138:in `mtime'
C:/Users/Bigdata-A/Documents/pin/軟體/網頁撰寫/fire.app.windows.1.14/fire.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/staleness_checker.rb:167:in `dependency_updated?'
org/jruby/RubyProc.java:271:in `call'
C:/Users/Bigdata-A/Documents/pin/軟體/網頁撰寫/fire.app.windows.1.14/fire.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/staleness_checker.rb:85:in `stylesheet_modified_since?'
C:/Users/Bigdata-A/Documents/pin/軟體/網頁撰寫/fire.app.windows.1.14/fire.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/staleness_checker.rb:73:in `stylesheet_needs_update?'
C:/Users/Bigdata-A/Documents/pin/軟體/網頁撰寫/fire.app.windows.1.14/fire.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/compiler.rb:211:in `update_stylesheets'
org/jruby/RubyArray.java:1613:in `each'
C:/Users/Bigdata-A/Documents/pin/軟體/網頁撰寫/fire.app.windows.1.14/fire.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/compiler.rb:209:in `update_stylesheets'
C:/Users/Bigdata-A/Documents/pin/軟體/網頁撰寫/fire.app.windows.1.14/fire.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/compiler.rb:293:in `watch'
C:/Users/Bigdata-A/Documents/pin/軟體/網頁撰寫/fire.app.windows.1.14/fire.app/lib/ruby/compass_1.0/compass-1.0.3/lib/compass/sass_compiler.rb:46:in `watch!'
C:/Users/Bigdata-A/Documents/pin/軟體/網頁撰寫/fire.app.windows.1.14/fire.app/lib/ruby/compass_1.0/compass-1.0.3/lib/compass/commands/watch_project.rb:41:in `perform'
file:/C:/Users/Bigdata-A/Documents/pin/軟體/網頁撰寫/fire.app.windows.1.14/fire.app/fire-app.jar!/app_watcher.rb:18:in `watch!'
file:/C:/Users/Bigdata-A/Documents/pin/軟體/網頁撰寫/fire.app.windows.1.14/fire.app/fire-app.jar!/ui/tray.rb:571:in `watch'
--------------------------------------------------------------------------------------
監看的資料夾如下圖
(https://user-images.githubusercontent.com/31687957/56016012-82bf5700-5d2d-11e9-8c2c-f5a314c12a75.png)

我的 fireapp版本 1.14
        java版本 Version 8 Update 201

這資料夾的檔案之前是在mac中編輯的，那時在mac裡面用fireapp都沒甚麼問題，用的版本也是1.14。
之後移到windows上，我載了fireapp windows版本，第一次執行程式監看資料夾後，出現上面那些錯誤，
我也不死心Build Project許多次，結果都是得到一個html檔案，裡面還是空的。
我也從新下載fireapp跟java安裝，但都是一樣的結果。
請問我的fireapp出什麼問題? 或是sublime有什麼外掛類似fireapp可以推薦我?
在或是有類似fireapp的程式可推薦嗎?
謝謝大家耐心看完，我已經掙扎2天在看相關資訊了。

**Comment by tka** [comment]
請試試看把路徑都改成英文看看

如果可以的話，個人目前推薦轉移到 webpack 的解決方案

畢竟不只是這個專案應該不會再有更新，連底層的 ruby sass 都要結束了

**Comment by doublinlin** [comment]
謝謝，我已經把路徑改英文，也是一樣
會去試試看你推薦的 webpack，謝謝
